### ISSUE TITLE
add HV sawmill

### ISSUE THREAD

**Issue by AsumFace** [KaylebJay/tunnelers-bugz#1]
more speed and upgrade slots

**Comment by AsumFace** [comment]
:ballot_box_with_check:  code
:negative_squared_cross_mark: textures

**Comment by KaylebJay** [comment]
I can do the textures :) 
Testing https://gitlab.com/h2mm/technic/-/merge_requests/12

**Comment by KaylebJay** [comment]
The problem here is that machine_base pastes these textures on HV machines. Look at this:
![screenshot_20200228_104059](https://user-images.githubusercontent.com/44441970/75571691-ee2e1800-5a16-11ea-9595-88422d300182.png)

**Comment by KaylebJay** [comment]
https://gitlab.com/h2mm/technic/-/merge_requests/12
