### ISSUE TITLE
[Manual tractor] & [Planter]  vs Privileges

### ISSUE THREAD

**Issue by Guilll4um** [KaylebJay/tunnelers-bugz#106]
at InitialD public farm (400,y,-300) i can harvest  with manual tractor (mode 6) on the open area, but i cant replant with planter (mode 6).
is it normal ? or maybe i do somthing wrong ? 

ty :)

**Comment by KaylebJay** [comment]
@AsumFace Can you check this out? Maybe its a simple fix(ish).
It seems that the tractor is harvesting the nodes which are in the open_area whereas the planter (though it is technically planting inside the open_area) is actually clicking (pointed_thing.under) on the protected dirt, and thus won't plant. I remember this issue from DWJeremy's Public Farm (back when it existed). There should be some simple workaround for this.

**Comment by AsumFace** [comment]
fixed by https://gitlab.com/h2mm/technic/-/merge_requests/35
