### ISSUE TITLE
Explody potion can be used for griefing and PvP

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#107]
So far as I know, I'm the only one w/ them so far (though of course they're on sale for a very steep price...). They don't damage protected areas, but they can damage surface areas, and kill other players even in protected areas (though so far, i've been more successful in killing myself).

This could all be expected, but I'd like to make sure.

**Comment by KaylebJay** [comment]
I should check if the area is above, say, -100, and make sure the obj is not another player.
The way I did it makes it still theoretically possible to damage the player, but you can't do it above ground and I doubt anyone would do that anyways (lava PVP is possible, too :P)

**Comment by KaylebJay** [comment]
Done
