### ISSUE TITLE
Infinite Moths

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#109]
1) If you use a bottle on a moth, you receive a moth in a bottle, but the bottle is not used up.
2) If you place and break a moth in a bottle, you release a moth, but still get back a moth in a bottle.

**Comment by KaylebJay** [comment]
ouch. Fixed in https://github.com/KaylebJay/petz/commit/5b8c9a350f8ab691d89a4da3fd53afc854ce7e1c
