### ISSUE TITLE
Foxes should be passive

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#114]
Also, arctic_fox and foxy should be the same. @fluxionary do you know of any way to 'alias' entities? Would be really helpfu, since I don't want to go the 'unknown entities' route

**Comment by fluxionary** [comment]
I *think* you can just alias them like anything else. Does that not work? 

However, if you do alias them, you might potentially get some issues due to the entity having the wrong metadata.

**Comment by KaylebJay** [comment]
Tried minetest.register_alias for entities, didn't work. Maybe I did something wrong? Yes, metadata is a problem, but the foxes are identical in metadata except texture :))

**Comment by fluxionary** [comment]
If `register_alias` doesn't work, you can probably change the ID of the entity when de-serializing it. When did you fork off the main petz, again? I can probably find you an approximate place in the code, but I know the current version is totally different.

**Comment by KaylebJay** [comment]
Does that work?! We forked off about here https://github.com/runsy/petz/tree/709265a6c2256bf6e9cbe7ba493323c67b554eeb

**Comment by fluxionary** [comment]
so, the way i might do this, is inside `petz.set_initial_properties`. I'd check to see if `self` was an arctic fox, remove myself, and put a regular fox in place. not super simple, and a bit hacky, but certainly do-able.

**Comment by KaylebJay** [comment]
Good idea. I'll try it.

**Comment by KaylebJay** [comment]
Fixed.
