### ISSUE TITLE
Moretrees improvements

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#116]
Replaces #115 which was made in haste.
- [x] force alias `moretrees:jungletree_trunk` to `default:jungletree`
- [x] Turn the apple tree in moretrees into default:tree, default:leaves, default:apple instead of the moretrees nodes (remove them)
- [x] Do the same as above again, but for turning moretrees palms into ethereal palm nodes and removing the moretrees ones.
- [x] force alias `moretrees:beech_trunk` to `default:tree`

**Comment by KaylebJay** [comment]
Working on this now. Hmm, does force_alias make all the moreblocks/mymillwork nodes go away too? I guess I'll have to see for myself :)

**Comment by fluxionary** [comment]
Not sure what's up for mymillwork, but for moreblocks you want `stairsplus:register_alias_force_all(modname_old, subname_old, modname_new, subname_new)`

**Comment by KaylebJay** [comment]
OOoooh, nice! Thanks flux :)

**Comment by KaylebJay** [comment]
Done in secretz. Also included recipes for the moretrees saplings (as now, they can't be gotten normally).
