### ISSUE TITLE
Infinite Free Garlic

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#117]
1) Craft 8 cloves into 1 head
2) Turn 1 head into 10 cloves in the thresher
3) Repeat

Best solution I can think of:
1) Require 9 cloves to craft a head
2) Only give 9 cloves when threshed

Alternate solution:
Disable crafting of heads from cloves.

**Comment by KaylebJay** [comment]
https://gitlab.com/h2mm/technic/-/merge_requests/36
