### ISSUE TITLE
Bug with drill

### ISSUE THREAD

**Issue by camiu01** [KaylebJay/tunnelers-bugz#118]
If you drill a drower they drop only the drower with out the item inside or upgrade

**Comment by KaylebJay** [comment]
This is interesting ... @AsumFace should the technic drill not dig the node if it is a drawer, or what do you think?

**Comment by AsumFace** [comment]
> This is interesting ... @AsumFace should the technic drill not dig the node if it is a drawer, or what do you think?

Most item containers aren't diggable as long as they aren't empty, drawers should conform to that.

**Comment by KaylebJay** [comment]
https://gitlab.com/h2mm/technic/-/merge_requests/37
