### ISSUE TITLE
Pull in staffs update (many-trees by duckduck)

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#122]
Now that all trees are compatible with bonemeal, this update makes sense.
https://gitlab.com/KaylebJay/minetest-staffs/-/commit/3b6baa53905059063584abb484e85fbd4ddde1cb

**Comment by KaylebJay** [comment]
Done in minetest-africa

**Comment by johann-lau** [comment]
Thanks
