### ISSUE TITLE
Grindable to raw materials

### ISSUE THREAD

**Issue by johann-lau** [KaylebJay/tunnelers-bugz#124]
Grindable Materials
As you can see in the crafting grid, Steel, wooden, obsidian and glass door can be grinned back to their raw materials, like sawdust, glass fragments and obsidian shard. This also applies to trapdoors, but how about prison doors? What about elevator doors?

- 3 Prison doors → Grinding → 8 wrought iron dust
- Glass elevator door → Grinding → 6 glass fragments
- Steel elevator door → Grinding → 6 wrought iron dust
- Tin elevator door → Grinding → 6 tin dust

**Comment by KaylebJay** [comment]
Merging with #123
