### ISSUE TITLE
Steel bar prices

### ISSUE THREAD

**Issue by johann-lau** [KaylebJay/tunnelers-bugz#125]
(Sorry for posting 3 issues at once)
Take a look at the cost of steel bars from inventory.
Imagine you need 144 steel bars.
If you use recipe 1, you need 64 wrought iron ingots.
If you use recipe 2, you need 54 wrought iron ingots only!
How is that possible ⁇

**Comment by KaylebJay** [comment]
Ugh, that's weird. I'll remove that recipe

**Comment by KaylebJay** [comment]
Can't fix. The recipe is there because of a conflict with another recipe that *sometimes* occurs (depends on how the restart happens, I think). So the cheaper recipe, you'll have to use.
