### ISSUE TITLE
Crystal Madness

### ISSUE THREAD

**Issue by johann-lau** [KaylebJay/tunnelers-bugz#126]
Try putting a crystal grass on top of another.
That’s why my 55 grass can’t fill in a crystal farm 40 nodes large.

**Comment by KaylebJay** [comment]
That's by design ;)

**Comment by johann-lau** [comment]
What?
In a laggy environment, it is unfair to poor players!

**Comment by johann-lau** [comment]
By design?

**Comment by KaylebJay** [comment]
Yeah, right-clicking a plant on a plant will place the plant on the plant. Its definitely by design because it works this way on any plant, including in MTG :)

**Comment by johann-lau** [comment]
But when I dig it, it gives me only 1 grass instead of 2
