### ISSUE TITLE
traffic cone protection

### ISSUE THREAD

**Issue by Guilll4um** [KaylebJay/tunnelers-bugz#13]
traffic cones can be taken by people who don't get permission on a protected area 

(sorry for my english i'm french)

**Comment by KaylebJay** [comment]
Really? Can you give the itemstring, please, so I can test?

**Comment by KaylebJay** [comment]
The item actually wasn't in a protected area and works with protection just fine. Thanks for report anyway, though :-)

**Comment by Guilll4um** [comment]
:S lol sorry it was at the limitof my protected area  i dont take care enought lol
