### ISSUE TITLE
Tarantulas don't burn in lava.

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#130]
Tarantulas don't take any kind of damage when they are swimming in lava. I think, this wasn't intended.

**Comment by KaylebJay** [comment]
That's odd, definitely not intended behaviour.

**Comment by KaylebJay** [comment]
A few other mobs had this 'feature'. Fixed in https://github.com/KaylebJay/petz/commit/e64856149a91c9cda57eaa0e2d5862336efaae73
