### ISSUE TITLE
mint from africaplants ported to farming?

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#131]
https://notabug.org/TenPlus1/farming/commit/f6a61994e474090b4ca02bbc89485447f4ab6b3f

Advice welcome.

**Comment by fluxionary** [comment]
The mint in farming looks horrible compared to the africaplants one :\

**Comment by KaylebJay** [comment]
true. I like to think of them as flora rather than a crop, too.
What might be better is porting the usecases found in farming for farming's mint.

**Comment by sivarajan931** [comment]
well it can be better for me :D

**Comment by KaylebJay** [comment]
dropping this idea, our mint is better
