### ISSUE TITLE
Drawer entity

### ISSUE THREAD

**Issue by johann-lau** [KaylebJay/tunnelers-bugz#132]
Put something in drawers and take it.
The entity still appears although it is “empty”.
This might cause confusion of what you have and what you don’t.

**Comment by fluxionary** [comment]
That's intentional, so that the "drawer controller" (?) can route things to the right place.

**Comment by KaylebJay** [comment]
Pretty sure that's supposed to be. oh, what flux said ^ :)

**Comment by johann-lau** [comment]
?????
