### ISSUE TITLE
illumishrooms *may* not appear in caves anymore

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#142]
I haven't confirmed this, but InitialD believes it and I haven't found evidence to the contrary yet. I'll close this if I find a counterexample.

EDIT: he also says he thinks it's only the green and blue mushrooms, but I haven't found any red ones in a new area since i've been keeping an eye out. But I think we need to check for all 3 varieties now.

**Comment by KaylebJay** [comment]
Cyan illumishrooms, I have confirmed, *do* spawn in matrix areas - just super rare and in a certain biome, it looks like. I'm not sure about green ones. Red ones are all over in amphibolite caves near the surface. However, green ones are a rarity on purpose afaik - I haven't seen them in matrix areas but this isn't a crisis yet and will make it a rarer item :)

**Comment by fluxionary** [comment]
I'm guessing you could tell by looking at the code? Are we using stock ethereal, or is it in a private repo?

**Comment by KaylebJay** [comment]
(mostly) stock ethereal. For the record, Osmium not spawning in matrix areas is a feature.

**Comment by fluxionary** [comment]
I know about the osmium, I asked about that a long time back. In any event, I presume you're happy w/ the current situation and will close this. It's not like there aren't other (semi-secret) ways to get green illumishrooms.

**Comment by KaylebJay** [comment]
Ok, then. :)
