### ISSUE TITLE
unified inventories plus ignores metadata

### ISSUE THREAD

**Issue by AsumFace** [KaylebJay/tunnelers-bugz#143]
`craft_organize.lua` is written in such a way that all attached item metadata gets discarded, this may destroy items or permanently break their functionality.
Instead working with item names and quantities and constructing `ItemStack`s from them, it should only mutate the existing `ItemStack`s.

**Comment by KaylebJay** [comment]
Oh, that's really bad.

**Comment by BuckarooBanzay** [comment]
Upstream issue: https://github.com/bousket/unified_inventory_plus/issues/8

**Comment by KaylebJay** [comment]
https://github.com/KaylebJay/unified_inventory_plus/commit/90a88f1e5d692b3c94690013a95031fcffadf1a0
Thanks Buckaroo for the commit!
