### ISSUE TITLE
playereffects prints a lot of debug stuff at server startup

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#144]
At server startup, the mod playereffects prints a lot of debug stuff which doesn't seem to be useful at all.

It looks like this:
```
2020-06-08 08:27:18: [Main]: [playereffects] inactive_effects = {
        abdrrhmn = {

        },
        geravane = {

        },
        noe = {

        },
        Andromeda = {

        },
        Hiccstrid = {

        },
        MaRiNeLa = {

        },
(...)
```
It prints approx. 2300 lines of this crap.

**Comment by KaylebJay** [comment]
Fixed @ https://gitlab.com/KaylebJay/minetest-africa/-/commit/7fbb9e5f44ac4f7023b9392dceaa5a74ad4d0a09
