### ISSUE TITLE
issue with digtron

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#146]
`2020-06-14 02:35:57: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod '' in callback environment_Step(): /home/vpsuser/minetest/bin/../mods/digtron/util.lua:55: attempt to call field 'can_dig' (a boolean value)`
`2020-06-14 02:35:57: ERROR[Main]: stack traceback:`
`2020-06-14 02:35:57: ERROR[Main]: 	/home/vpsuser/minetest/bin/../mods/digtron/util.lua:55: in function 'mark_diggable'`
`2020-06-14 02:35:57: ERROR[Main]: 	...user/minetest/bin/../mods/digtron/nodes/node_diggers.lua:408: in function 'execute_dig'`
`2020-06-14 02:35:57: ERROR[Main]: 	...user/minetest/bin/../mods/digtron/util_execute_cycle.lua:151: in function 'execute_dig_cycle'`
`2020-06-14 02:35:57: ERROR[Main]: 	.../minetest/bin/../mods/digtron/nodes/node_controllers.lua:148: in function 'func'`
`2020-06-14 02:35:57: ERROR[Main]: 	/home/vpsuser/minetest/bin/../builtin/common/after.lua:20: in function </home/vpsuser/minetest/bin/../builtin/common/after.lua:5>`
`2020-06-14 02:35:57: ERROR[Main]: 	/home/vpsuser/minetest/bin/../builtin/game/register.lua:429: in function </home/vpsuser/minetest/bin/../builtin/game/register.lua:413>`

**Comment by BuckarooBanzay** [comment]
maybe related: https://github.com/pandorabox-io/pandorabox.io/issues/363

**Comment by KaylebJay** [comment]
Ah ha! I put can_dig = false in the definition of my custom dummy light node, to prevent lasers from collecting it. `LadySparkles25` reported this was just after she jumped in front of the digtron, so she must have been wielding a torch. I'll fix that - thanks, Buckaroo :)

**Comment by KaylebJay** [comment]
Done (upstream).
