### ISSUE TITLE
ebony tree bugz

### ISSUE THREAD

**Issue by Guilll4um** [KaylebJay/tunnelers-bugz#148]
when i cut wood of the  ebony tree, got more wood in inventory than i cut with the adamantite chainsaw =)

**Comment by KaylebJay** [comment]
@AsumFace is this the same duplication bug as before?!

**Comment by KaylebJay** [comment]
@Guilll4um Tested in-game and the wood drop seems correct. Can't find any duplication?

**Comment by Guilll4um** [comment]
got the 5.2.0 client with some client mods

was on africa server near andreasbaders plantation
and  CalebJ africa base ... i'm trying to  find the location again but i dont remember where it is

**Comment by Guilll4um** [comment]
i found  and reproduce the bug , was not when cutting the wood , but when placing like that on that tree ! [image](https://user-images.githubusercontent.com/61607614/84628450-f4260700-aee8-11ea-9ade-4c12ef9d4f11.png) <== click to got coordinates


i cut so got 4 wood in the inventory,
![image](https://user-images.githubusercontent.com/61607614/84628573-30596780-aee9-11ea-834b-e585b3960202.png)
then when i want to put the wood trunc here i got always 4 in inventory
![image](https://user-images.githubusercontent.com/61607614/84628625-4ebf6300-aee9-11ea-9545-1ec79fce2557.png)
=)

**Comment by KaylebJay** [comment]
@Guilll4um Ah, sorry, I misunderstood. A dangerous bug! Can you test if this works with all cool_trees? (jacaranda, ebony, lemontree, larch, clementine, chestnut) Does it work with minetest-africa trees?

**Comment by Guilll4um** [comment]
it's me ! first i belive it was when cutting :)

ok i check that !

**Comment by Guilll4um** [comment]
i test almost all species in the botanic  (about 59 species so all except australia and new zealand) ... and ....
the bug not depend on the wood trunc you got in hand but on the wood on which you want to put the trunc ... so it seems any kind of wood can be multiply like that.
when putting the trunc on :
![image](https://user-images.githubusercontent.com/61607614/84697475-7a286900-af4e-11ea-8c23-c1f874adeb7e.png)

- **cherry** trunc
- so **ebony** trunc
- **larch** trunc
- **candelabra** trunc
- **jarcananda** trunc
- **wood cyclad** trunc

@KaylebJay  with the **citrus** was different behavior i cant put back the trunc :/
![image](https://user-images.githubusercontent.com/61607614/84697526-9af0be80-af4e-11ea-9ea9-9b0549b51d9a.png)

**Comment by fluxionary** [comment]
I wonder if this is a regression related to #67

**Comment by KaylebJay** [comment]
Flux, it seems to be, yes. 
Interesting, Guill, I will see what might have caused this.

**Comment by Guilll4um** [comment]
yes **CeeJay** ! my poor citrus trees 🤕  lol  ... 
yes **Flux** it look likes a lot  well done :p

**Comment by KaylebJay** [comment]
> so it seems any kind of wood can be multiply like that

Really? Try with default, aotearoa, australia, or ethereal? I think it shouldn't work.

**Comment by Guilll4um** [comment]
default wood multiply on cherry (one of those 6 above)
![image](https://user-images.githubusercontent.com/61607614/84715802-dea8ef80-af71-11ea-8640-629328db42ab.png)

**Comment by KaylebJay** [comment]
ohhhh ... UGH, this needs to be hotfixed.

**Comment by KaylebJay** [comment]
I will also check out the logs for anyone abusing this bug. I think I have a working fix now.

**Comment by KaylebJay** [comment]
Fixed, thank you very much for report @Guilll4um!
