### ISSUE TITLE
Flowing lava and slime textures are weird

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#15]
The flowing lava and slime textures are weird. They are wobbly but they don't actually flow anywhere. The flowing lava texture looks like a sequence of random frames. Flowing slime seem to flow sometimes downwards and sometimes upwards.

**Comment by KaylebJay** [comment]
Lava is fixed - Slime will also be by the end of today.
Now it flows directly outward, extremely slow but not wobbly.

**Comment by Hypernoot** [comment]
The slime doesn't seem me to be flowing at all. By "flowing", I mean that when you watch a wave on the texture, it moves from the top side to the bottom in finite time. All waves here seem to stay at the same spot. The slime isn't flowing at all, not even slowly.

**Comment by KaylebJay** [comment]
Fixed in secretz, stable and approved by several users nouw.
