### ISSUE TITLE
Find a use/replacement for ducky/chicken nests

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#150]
- [x] Chickens and ducks need to be breedable somehow
:x: The eggs should be hatchable somehow (without nests)

**Comment by fluxionary** [comment]
technically, you could keep the current mechanics w/ nests, and address the current issues w/ (admittedly modest) geometrically growth, by i.e. predicating the expected time needed for a nest to produce an egg with the number of neighbouring (or nearby) nests.

**Comment by KaylebJay** [comment]
Yes, but I don't like that method anyways. ElCeejo's suggestion sounds nice, but also would have significant lag side effects.

**Comment by KaylebJay** [comment]
Currently the eggs can't be laid in the nest anymore. So ... 

If we were to keep the nests (I don't like it but it might be the best way), there are two methods:
1. The player would then have to put the egg in the nest and wait for the mother to incubate it(?)
2. The egg could hatch without the mother in the nest (doesn't make sense)

If we were to remove the nests, there are also a few ideas:
1. Chickens could give live birth (o_O), and eggs could be throwing objects to knock players back
2. Chickens could just lay eggs as normal and eggs could be hatched using some machine (incubator?)
3. Chickens could incubate egg(s) by right-clicking it on them (would show in the formspec) and waiting.

**Comment by fluxionary** [comment]
Another option:
You could leave the nests in, as a purely decorative object. Players could place/remove eggs from the nests. Reproduction could be done otherwise by whatever method you prefer.

**Comment by KaylebJay** [comment]
Hmmm, sounds like a good idea. :thumbsup:

**Comment by KaylebJay** [comment]
Done in petz:paleotest. Chickens are now breedable and eggs are only laid if the chicken is tamed and not a juvenile.
The eggs are infertile, because all these chickens seem to be females ...

**Comment by KaylebJay** [comment]
Oh, speaking of which, I should make males not have the ability to lay eggs ...
EDIT: done

**Comment by fluxionary** [comment]
> Oh, speaking of which, I should make males not have the ability to lay eggs ...

yeah, better watch out, that's how you get basilisks..
