### ISSUE TITLE
boat boat boat ! .... when right clicking on a boat already used

### ISSUE THREAD

**Issue by Guilll4um** [KaylebJay/tunnelers-bugz#161]
when **right clicking on a boat already used** by someone else  ( here frost princess :p ) :
![image](https://user-images.githubusercontent.com/61607614/85466540-64e4b780-b5aa-11ea-9452-96d4cc700ad8.png)

- you have to use /killme to unstick the boat,
- you can control the boat
- when killed  and restart at spawn you keep the camera behavior of the boat one : (look where is the selection box)
![image](https://user-images.githubusercontent.com/61607614/85466825-bb51f600-b5aa-11ea-86b4-ed4b782486d7.png)

ty for all the job on the server !

**Comment by KaylebJay** [comment]
Looks like the correct way to fix this is by checking in on_rightclick, if self.driver ~= nil and if it is, return end.

**Comment by KaylebJay** [comment]
Fixed! Thanks for report.
