### ISSUE TITLE
Investigate the weird moretrees:palm_fruit_trunk node

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#164]
Coconut palms may grow these weird nodes which don't lie in any groups and they can't be punched down by a chainsaw. They are defined at cocos_palm:41. They seem to be used for regrowing the coconuts but it looks like it's not always handled correctly. This needs to be investigated.

**Comment by KaylebJay** [comment]
Fixed by you :D
