### ISSUE TITLE
Compactor eats xtraores blocks

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#166]
Creating compressed xtraores blocks in the Compactor requires 9 blocks, but 8 in the Compressor. Probably best to just remove them from the Compactor.

**Comment by Guilll4um** [comment]
dont remove cobble compacting from compactor ! : S (idk if you are speaking about that coz of my bad english)

**Comment by fluxionary** [comment]
this is for things like adamantium, cobalt, platinum etc., not cobble

**Comment by Guilll4um** [comment]
ho ok  ty !  ': )

**Comment by AsumFace** [comment]
here you go https://gitlab.com/h2mm/technic/-/merge_requests/43
