### ISSUE TITLE
Wolfs do not breed

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#17]
... cause unknown, further testing needed.

**Comment by fluxionary** [comment]
I've also been unable to breed cows for a while. Is it still supposed to require blueberries? I've tried both kinds. Attempting to feed them just brings up a dialog box to rename them and stuff. I can still feed them wheat to heal them though.

**Comment by KaylebJay** [comment]
I figured it out, and both should work now. Closing as soon as petz is pulled

**Comment by KaylebJay** [comment]
Fixed (secretz, petz pulled today)
