### ISSUE TITLE
Missions items should probably not be craftable

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#18]
I don't think you can do anything w/ them w/out the permissions, but it'd probably be best if players weren't confused by them.

**Comment by KaylebJay** [comment]
You certainly can! LadyK made her own, without any missions related priveledges. Try it for yourself, anybody can make a mission.

**Comment by Hypernoot** [comment]
You should add a label "feature" :D

**Comment by fluxionary** [comment]
Oh, I didn't even realize players could make missions! I'll have to look into that some time. 

I'm closing this now because it's not actually an issue.
