### ISSUE TITLE
The xdecor pressure plates disappeard !

### ISSUE THREAD

**Issue by Guilll4um** [KaylebJay/tunnelers-bugz#190]
![image](https://user-images.githubusercontent.com/61607614/86522519-7dcd5280-be5f-11ea-9440-d3688b35f4d6.png)

maybe it's coz of the new recipe of mesecon one ?

**Comment by KaylebJay** [comment]
I should have aliased them to the mesecons one. 
https://github.com/KaylebJay/tunnelers-bugz/issues/30

**Comment by Guilll4um** [comment]
why you do that just after i precise to keep them coz of different behavior ?

![image](https://user-images.githubusercontent.com/61607614/86522588-94c07480-be60-11ea-8b8e-a871f36acfec.png)

**Comment by Guilll4um** [comment]
keep them was the reason of adding a mescon to the recipe of the mesecones ones  : S

**Comment by Guilll4um** [comment]
i was using them find as the best soluce for my door and for security without any bug since i'm playing

**Comment by KaylebJay** [comment]
Good point. We should re-add them but we need Hume2's opinion since he wanted them removed.

**Comment by Guilll4um** [comment]
ok :)

**Comment by fluxionary** [comment]
It sounds like you plan to re-add them, but I just wanted to butt in and say that aliasing the xdecor ones to the mesecons ones isn't a good idea, as mesecons nodes need to execute logic during `on_construct`. You'd need to use an LBM to convert them, and players would be left w/ unknown nodes in their inventory.

**Comment by Guilll4um** [comment]
And it's not the same behavior with iron door ! 

 and aliasing them you are making security breach on iron door driven by xdecor pressure plate
doing that, for example, all guys could enter the private parts of my base >_<

**Comment by Guilll4um** [comment]
i'm sure making protected iron door with pressure plate best way is : iron door + xdecor pressure plate  (that might use onwer metadata of iron door i think  ) 
...

coz with mescon it need player detector  + mescon dectector + lua controller or logic gates ... that i think are more server demanding :) ... and in little space you cant use that without destroying all and reworking all.. i spend sevral hours to study the best way to put that doors and pressure plate in underground narrow corridors , close to each other, and asking other player to test the behavior according to the ownership.

in a word if you delete these pressure plate i got to rework all my base , i will have to destroy all and redo all :) ... it's not important but it's to show that xdecor pressure plate are very usefull when you want to do sharp things :) that are very different of wot you can do with mescon ones :)

**Comment by Hypernoot** [comment]
suggestion:

xdecor stone pressure plate -> steel pressure plate
xdecor wooden pressure plate -> bronze pressure plate

**Comment by Guilll4um** [comment]
yes could be good .. with aliasing them of course ! to repair all unknow nodes of them in the world  : p
and keeping same behavior than before

**Comment by fluxionary** [comment]
Just for reference, after experimenting w/ unifying them on BlS, I decided it was too complicated. This was my solution:
https://github.com/BlockySurvival/bls_custom/commit/36f10554e2efd188e815bf7ffeff3eed2431ccf5#diff-3f1bdbf4ec3f54b2665d89474895625dR631-R668

**Comment by Guilll4um** [comment]
nice 
i love the changed recipe i do just before, adding  mescon wire to  the mesecon one  to show they dont got the same behavior at all :)

**Comment by Guilll4um** [comment]
as far as i'm conserned , i 'm waiting a choice to start playing again with my full base :) i cant access to my base and i dont want to detroy all doors if nothing change :)

**Comment by KaylebJay** [comment]
WAAAAAAAT ... you can minetest.clear_craft? that's SOOOOO awesome!!

@Guilll4um I will be back to minetest tomorrow (holidays). So sorry for the delay! :S

**Comment by KaylebJay** [comment]
Hume2's suggestion is what I will implement. If anyone wants to make a pull request, https://github.com/KaylebJay/xdecor is what we use. A minetest.register_alias(olditem, newitem) will be needed to convert the old nodes (metadata would be the same, just a naming/(texture maybe?) change.

**Comment by Guilll4um** [comment]
it's ok @KaylebJay  i finally decided to open just one door to access my drawers room :)

if you're asking if somone can implement that for you i'm ready ... coz drawers are finished (testing) ... 
even  if i'm noob at those stuff :)

**Comment by KaylebJay** [comment]
Go for it, @Guilll4um :) I'm about to leave on a day trip so I won't be able to review/merge it until tonight.
Great to hear that the drawers update is finished!!! :))

**Comment by Guilll4um** [comment]
```lua
		local minp = {x = pos.x - 2, y = pos.y - 1, z = pos.z - 2}
		local maxp = {x = pos.x + 2, y = pos.y + 1, z = pos.z + 2}
``` 
here the famous 2 nodes that make xdecor pressure plate open doors around

![image](https://user-images.githubusercontent.com/61607614/86604581-d9a1f380-bfa5-11ea-9f73-3c4cc5212785.png)
i think the guy put 2 nodes so you can make symmetrical things :)

**Comment by Guilll4um** [comment]
but this can be improve 
activating only door that are put just in the middle (not at  any  other side of the same  node) and facing the prerssure plate

**Comment by Guilll4um** [comment]
for betterr understanding  with this picture we can :
- green =  autorise the pressure plate to open door.
- red = forbbid pressure plate to open the door
- yellow = autorise only door that are jsut near the green node like the wooden door on the picture bellow :)

**wot do you think about that ?** ... and it's less node to check ! (currently all these nodes are checked )
i think  the yellow case is the most used case and this will not break doors openning on the server

![image](https://user-images.githubusercontent.com/61607614/86605937-9e082900-bfa7-11ea-96a5-f36c3f1853bd.png)

**Comment by KaylebJay** [comment]
That's a good idea, Guill.

**Comment by Guilll4um** [comment]
i'm always on the pressure plate ! 
it's almost done 

i'm preventing doors claping when we stay on the pressure plate :)

**Comment by KaylebJay** [comment]
https://github.com/KaylebJay/xdecor/pull/2

**Comment by KaylebJay** [comment]
Fixed by Guill4um - thanks!
