### ISSUE TITLE
Head's up: change in the behavior of minetest.get_connected_players()

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#20]
Due to [a recent change in the Lua API](https://github.com/minetest/minetest/issues/9428), `minetest.get_connected_players()` now returns `nil` instead of `{}` if called before the game is initialized, which can cause mods that don't check for that behavior (probably most of them that are doing this) to crash the server before it starts. Before the next time you update the game engine, you should make sure that none of the mods do this.

**Comment by fluxionary** [comment]
(also i apparently don't have the ability to assign a label)

**Comment by KaylebJay** [comment]
You should be able to now, I invited you. Thanks for this warning, why is this even a problem in the first place? 'nil' instead of {} seems like a major overlook.
