### ISSUE TITLE
(most) mushrooms don't spread

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#22]
Only the default red mushrooms (the amanita muscaria looking ones) do. Was `group:mushroom` removed from brown mushrooms intentionally? 

It'd also be neat if the other mushrooms could spread (excluding the glowing ones, i suppose, they'd keep themselves from spreading using the logic in minetest_game).

**Comment by KaylebJay** [comment]
That'd be weird if the brown mushrooms didn't grow, you sure? 
Its a pretty simple fix if true :-)

**Comment by fluxionary** [comment]
It's easy to check that they're not in `group:mushroom` (search in unified inventory) and i also tested that they don't spread.

**Comment by KaylebJay** [comment]
What other mushrooms would you like to add to this? Some itemstrings would be very useful :)

**Comment by KaylebJay** [comment]
This doesn't make any sense at all. Not only are they are in group:mushroom in the source code but also the ABM specifically defines flowers:mushroom_brown and flowers:mushroom_red as the ones to operate on.

**Comment by fluxionary** [comment]
* underch:black_mushroom
* underch:green_mushroom
* underch:orange_mushroom
* underch:dark_tuber
* africaplants:cortinarius_violaceus
* africaplants:orange_mycena

**Comment by fluxionary** [comment]
Oh, interesting, so it does, it's different than flower_spread (which acts on group:flora) and I didn't realize that. Still pretty sure brown mushrooms aren't spreading, but let me AFK at my mushroom farm a bit longer.

**Comment by fluxionary** [comment]
Alright, my brown mushroom spread. Which is bizarre that the first one happened now, given that my red one has bloomed into 15 or 20 already. I'm still confused as to why the brown mushroom isn't in group:mushroom, but as the rest of this requires writing new code, I'm okay if you decide to drop it.

**Comment by KaylebJay** [comment]
Thanks for info. Yeah, it'd just be really weird if they didn't spread.
I think those mushrooms really should be spreadable. Lets see if I can find a way without writing a new ABM :)

**Comment by KaylebJay** [comment]
I've found a way & this will be a part of the secretz update.

**Comment by KaylebJay** [comment]
Done in Secretz (added today)
