### ISSUE TITLE
Saddles still disappear if a horse is unloaded

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#23]
Most annoyingly, this happens if I hit an unloaded mapblock while riding the horse. 

I'm guessing the fix hasn't been pushed to the server? What's the hold up? Given that cows are unbreedable and the plastic/titanium saddle recipe isn't in place either, it's really hard to make new ones as quickly as I lose them.

**Comment by KaylebJay** [comment]
Yes, it hasn't been pushed to the server. This might happen tomorrow.

**Comment by KaylebJay** [comment]
Cows are breedable AFAIK, I did that earlier?

**Comment by fluxionary** [comment]
I used to breed them, but they won't eat blueberries anymore. Do they have a limit on the number of times they can breed, like horses?

**Comment by KaylebJay** [comment]
Secretz added, this is fixed.
