### ISSUE TITLE
Pull in barter table update from currency mod

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#24]
See https://gitlab.com/VanessaE/currency/-/commit/2d7d2dd206db24a35cddff3618cc798a792257c6

**Comment by fluxionary** [comment]
(not sure what label to give this)

**Comment by KaylebJay** [comment]
This is nice... And a good feature to pull in. The problem is, when ...

**Comment by KaylebJay** [comment]
Done by Hume2 and live now.
