### ISSUE TITLE
Drawers: some spalings don't got drawer preview icon

### ISSUE THREAD

**Issue by Guilll4um** [KaylebJay/tunnelers-bugz#27]
![screenshot_20200310_181357](https://user-images.githubusercontent.com/61607614/76344931-ad7dab00-6302-11ea-8fe3-64307d85a0fb.png)

the list :
- rimu
- manuka
- pohutukawa
- kawakawa
- kauri tree
- karo
- karaka

=)

**Comment by KaylebJay** [comment]
Thanks for this. I'm not sure what causes it, will have to look into the code :)

**Comment by KaylebJay** [comment]
Fixed by https://gitlab.com/h2mm/aotearoa/-/commit/608557a40074f0af706f274fa406804924c6109c
