### ISSUE TITLE
Horses should be placable in protected areas

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#28]
So I can ride them around towns

**Comment by KaylebJay** [comment]
Got to think about this a bit more. I see problems with this like mass petz griefing at spawn.

**Comment by fluxionary** [comment]
Yup, I agree there's potential issues, but I'm not sure how bad they are really. It's also why I said horses (and camels I suppose) but not all petz. 

As for the griefing, right now you could litter spawn w/ bicycles. No one does that.

**Comment by KaylebJay** [comment]
This is sadly worked into minetest.is_protected. Meaning even if I remove the minetest.is_protected check, it still won't work. So... I guess no more controversy - this can't be fixed for now. Guess finding an unprotected area, placing, and driving into protected areas is your best bet.
