### ISSUE TITLE
Remove pressure plates from xdecor

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#30]
The pressure plates from xdecor are buggy and useless. I suggest removing them completely or at least making them uncraftable.

1) The pressure plates open doors which are two nodes away for no apparent reason.
2) They don't activate mesecons at all
3) The wooden pressure plate has a conflicting recipe. It conflicts with the pressure plate from mesecons.

**Comment by KaylebJay** [comment]
Fixed in https://github.com/KaylebJay/xdecor/commit/dbe3da095ba94f46e456cd94369d0e78bb0231ea
