### ISSUE TITLE
Petz improvements

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#32]
- [x] Damage system improvements
- There is no way to currently know how much HP the petz has or how much you are damaging it. (EDIT: If it is tamed and named you can see the HP. That's actually decent, it doesn't clutter the world with so much text but you can still see HP from your own animals. I'll keep it like that for now, so 'done')
- The petz is knocked back when punched but other than that no indication that you are hitting it is present. (fixed)
- Some petz cannot be damaged by other petz, such as chickens vs. foxes. (not possible with current API it seems, so predators/prey will be for later)
- Petz should burn in lava or fire, with particle effects of course. (done - tarantulas now have the ability to teleport out of lava as soon as they receive damage)
- Petz should drown if they are in water and are not a water mob. (done)
- [x] Spawning needs rework
- Alpaca, bats, silkworms, and all water mobs do not spawn because of an issue in mobkit. (fixed)
- [x] New mobs added
- Tarantula, spawns in caves from hidden spawners and attacks players if they don't pay attention. (Done. Tarantula's can teleport from up to 50 blocks away with xray vision instead of using spawners :grin:, and have 40HP).
- Parakeet, breedable bird that spawns in cold forests. Has one mutation: Carolina Parakeet (done)
- Nyancat, peaceful animal that spawns underground and will be the rarest mob (node? :P) in the game. (done)
- Piranha, spawns in river water and can attack players but has almost no HP. Moves very fast. (done)
- Megamouth, a large shark with a healthy appetite that spawns in very deep oceans and can do special things. (done)
- Koala, peaceful animal that eats acacia trees and sleeps a lot. (done)

- [x] Textures should be 3 dimensional, like the models

- [x] Player experience enhancement
- Petz should have to be tamed to be able to lasso it. (done)
- Petz following players should not be so iffy. (done)
- Petz following players should also protect players if possible. (this will be done by paleotest instead)
- Saddlebags do not work currently. (fixed)
- Protectors do not work currently. (fixed)
- Water petz should be able to breathe too! (done)

**Comment by fluxionary** [comment]
* Megamouth could drop a shark tooth? 
* Koalas eat eucalyptus IRL. Did you mean Acacia?

**Comment by KaylebJay** [comment]
Yup, I think I've got a pretty good drop items for it now based on its teeth. Thanks! :-)
Well, Eucalyptus is most closely related to Acacia IRL, as far as I know, so since we don't have eucalyptus they will adapt and eat acacias :)

**Comment by fluxionary** [comment]
What do you mean we don't have eucalyptus! There's tons of varieties in Australia.

**Comment by KaylebJay** [comment]
Well, yer right there :D 
But should they spawn in australia and not the default world? :thinking:

**Comment by KaylebJay** [comment]
3D petz textures are now live on the server. :tada:

**Comment by KaylebJay** [comment]
Everything is now in the server *and* working. This has also dramatically reduced lag from petz.
