### ISSUE TITLE
Player model shrinks w/ specific horse interaction

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#37]
My player model shrinks to the size of an ant if I do the following:

1. Get on my horse
2. While on the horse, pick it up using a lasso

The effect is visible to me in 3rd person mode, as well as to other players on the server. In order to reset the effect, I have to relog, or remount the horse and get off w/ out the lasso. 

Example:

Normal:
![screenshot_20200322_062341](https://user-images.githubusercontent.com/25628292/77243864-d78a7380-6c06-11ea-87e3-5511d59dcba4.png)

Shrunken (outlined my model in red):
![screenshot_20200322_062253](https://user-images.githubusercontent.com/25628292/77243866-dc4f2780-6c06-11ea-8854-bcdb429128b1.png)

**Comment by KaylebJay** [comment]
Very impressive amount of diamonds you have there. :smile: 
I don't know if I'd call this a bug... players are using it to make themselves invisible. I know how to fix it but have refrained because too many players are using this 'feature'.. not sure what to do about this.

**Comment by fluxionary** [comment]
it seems like if there's going to be a way for players to become invisible, it shouldn't be a weird side effect of riding a horse.

**Comment by KaylebJay** [comment]
I'm very keen to fix this recently. 
I tried my previous fix, it won't work on 5.2.0-dev anymore. :-( I will keep trying.

**Comment by KaylebJay** [comment]
Fixed (sort of). It can't happen anymore at least.
