### ISSUE TITLE
Needless ABMs?

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#38]
The server currently runs ABMs at 1 second interval for all these nodes, individually. `advtrains:across_on` 
`advtrains:track_swl_st`
`advtrains:track_swl_st_45`
`advtrains:track_swr_st `
`advtrains:trackswr_st_45`
`advtrains:track_swr_cr`
`advtrains:track_swr_cr_45`
`advtrains:track_swl_cr`
`advtrains:track_swl_cr_45`
Problem is, none of these are even registered nodes from what I tested. Removing these would mean 9 less ABMs and these are big ones (running at one second).

**Comment by Hypernoot** [comment]
If I remember correctly, they are here to convert legacy items. We can definitely get rid of them.

**Comment by KaylebJay** [comment]
That's great! :D

**Comment by KaylebJay** [comment]
Done by Hume2
