### ISSUE TITLE
"neon" lamps from `elements` should be rotatable w/ the screwdriver.

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#39]
It'd make them much more fun - they'd look better on a ceiling (or even a wall) than the floor. 

A lesser priority "nice-to-have" would be a better hitbox.

**Comment by KaylebJay** [comment]
Totally! I'll do both.

**Comment by KaylebJay** [comment]
Because this is a mesh, I can't get the collision_box to register.
However, all (including krypton lamps) are now rhotatable.
