### ISSUE TITLE
Enhancement: fern tubers

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#40]
I've got a ton (12+ stacks) of ethereal ferns because they're somehow the end product of threshing various things, and was wondering what to do with them. Ethereal apparently has a "fern tuber", but I've never got one. I assume it's a rare drop if I'm breaking the plant nodes in the world. Australia also apparently has a fern tuber, not sure what's the deal w/ that.

I've got a couple proposals:
1. Threshing (some number) of ferns should give you fern tubers. 
2. One fern tuber item should be aliased to the other

**Comment by KaylebJay** [comment]
Should be cake, sure thing. Probably I'll slip this into secretz.

**Comment by KaylebJay** [comment]
Done
