### ISSUE TITLE
New mod: digistuff

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#41]
A player asked if there was a way to control the distance @ which a player detector works, and I had a solution, but with a mod that we don't have installed. 

https://cheapiesystems.com/git/digistuff

It has 2 kinds of player detectors that are programmable via luacontrollers, as well as a number of other goodies. Blocky Survival has had this mod since the very beginning (or just about), and it's quite stable. Cheapie was responsive for a couple of small issues I had, so it's not a mod you'd have to maintain. I don't recommend activating the NIC, it can import arbitrary images into the server. The mod wouldn't add a large number of nodes to the server, and won't cause any more lag than the use of luacontrollers already do.

**Comment by AsumFace** [comment]
It doesn't seem like there's much to do to extend the existing player detector to have that capability, in fact, I think copy&pasting the code from the node detector might just work.

**Comment by fluxionary** [comment]
> It doesn't seem like there's much to do to extend the existing player detector to have that capability, in fact, I think copy&pasting the code from the node detector might just work.

True; however, I feel like the mod has other useful mechanisms, and has the added bonus of not contributing to code that the admins have to maintain themselves.

**Comment by KaylebJay** [comment]
I'm for AsumFace's suggestion of making the node detector have more features instead of adding the whole mod. The whole mod will just not be added because it adds a lot of new nodes that have good (and laggy) features which I used to work with, and I don't want to revolutionize machines this late.

**Comment by OgelGames** [comment]
FYI, an adjustable player detector already exists in the `MoreMesecons` modpack: https://github.com/minetest-mods/MoreMesecons/tree/master/moremesecons_adjustable_player_detector

**Comment by KaylebJay** [comment]
I've seen the MoreMesecons modpack, it has some nice things - we could definitely incorporate some of it also. Thanks OgelGames!

**Comment by KaylebJay** [comment]
Done https://github.com/KaylebJay/mesecons/commit/ef09f547ad3e0a05af095e9b5c7935e5b17a64fa
