### ISSUE TITLE
Aluminium block from elements cannot be turned back into ingots

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#42]
Not that I have anything to do with the ingots, just checking if this is intentional or an oversight.

**Comment by KaylebJay** [comment]
Sorry about this, an overlook. Just fixed it.

**Comment by AsumFace** [comment]
Please tell me the node names so I can add a suitable recipe to the compactor.

**Comment by KaylebJay** [comment]
elements:aluminum_block, elements:aluminum_ingot
