### ISSUE TITLE
Elements recipe w/ unknown item

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#44]
`elements:uranium35_dust * 25` + `elements:flourine * 100` -> `uranium fuel rod` in the Atomic Constructor, however `elements:uranium35_dust` doesn't exist; i think you meant `technic:uranium35_dust`? (Also, that's a brutal recipe; it'd usually require only 5 dust and no fluorine in the compressor)

(also it's spelled fluorine, not flourine)

**Comment by KaylebJay** [comment]
Yeah, :bug:. But its not brutal because its outputting a uranium fuel rod. 
I just noticed that is a typo (flourine vs fluorine) along the whole mod. I think I'll just change the craftitem name, not the actual itemstring.
And done.

**Comment by fluxionary** [comment]
Hm, "brutal" i suppose depends on what the correct recipe is. If it's 25 3.5% dust, that's 5 times the amount a fuel rod takes normally; you could just smelt and compress your dust and get 5 rods, without having to ever even find fluorine (which, so far as i know, isn't easy to acquire large quantities of). If it's 25 `elements:uranium`, that's a good deal (if you have the fluorine)
