### ISSUE TITLE
`aorearoa:iron_sand` (probably) should not be in `group:sand`

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#46]
For one, this creates at least one weird recipe conflict

**Comment by KaylebJay** [comment]
I don't see why this is a bug. It is a type of sand.

**Comment by fluxionary** [comment]
Mostly, because it's mostly iron oxides, instead of silica, and doesn't make sense. But there's also a recipe conflict w/ smelting it - iron lump vs. glass.

**Comment by KaylebJay** [comment]
Ok, fixed.
