### ISSUE TITLE
Dungeons spawn much too infrequently at lower elevations

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#48]
Cause unknown, Diaeresis is investigating this.

**Comment by fluxionary** [comment]
I've seen several dungeons in obscurite below -30000, but now that you mention this, i feel like there's generally none (or almost none) inside matrix areas. I'm guessing that's related?

**Comment by KaylebJay** [comment]
Seems to be strictly associated with matrix, yeah.

**Comment by KaylebJay** [comment]
https://gitlab.com/h2mm/underch/-/merge_requests/1

**Comment by KaylebJay** [comment]
Diaeresis' dungeonz are working and live now. (and quite rare)
