### ISSUE TITLE
My criticism to cobble textures

### ISSUE THREAD

**Issue by Hypernoot** [KaylebJay/tunnelers-bugz#55]
The cobble textures are way better now. There are a few bugs though.
- Basalt cobble and andesite cobble look almost the same.
- Andesite cobble seems to lack the flakes unlike its smooth variant.
- Hektorite cobble doesn't quite match its smooth variant. The white flakes are missing completely.
- Phonolite cobble texture consists only of 5 unique colours.
- Amphibolite cobble and default cobble look almost the same.
- Still a lot of copypasta: There are four patterns which are used by 19 out of 28 cobbles from underch. They differ only in colour. The default cobble also uses one of these patterns.
- The smooth variants look like they have lost a lot of information, why was that done? Now the pattern repeats too often.

**Comment by KaylebJay** [comment]
7 has been fixed.
I'll work on 1-5 yet. I can incorporate more cobble pattern varients but I don't know how long that would take me.

**Comment by KaylebJay** [comment]
-Andesite can get its own cobble overlay. 
-Hektorite can get white flakes.
-Phonolite can get its own cobble overlay.
-Default cobble can get its own cobble overlay
That should fix all problems, I think.

**Comment by KaylebJay** [comment]
Finished!
