### ISSUE TITLE
Improve the farming side of petz

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#62]
- [x] make raw meats from petz edible (this really should already have been done)
- [x] make lambs regrow wool after eating 
- [x] increase breeding count to 3 or 4, to encourage breeding
- [x] make babies grow quicker?
- [x] port 'ducky_feather' to just 'feather', and have more animals drop it (for dreamcatchers)
- [x] make a 'cooldown' for breeding
- [x] use better foods for 'rut' (not just blueberries for all animals!)

**Comment by fluxionary** [comment]
Not sure if you're open to suggestions for other things here, but 
1. It'd be neat if there were more kinds petz drops (rabbit's feet, ...). Actually, now that I look through petz, there are quite a few other drops, I've just never seen them (beaver pelt, bee sting, frog legs, pollen (?!)). 
2. It'd be neat if there were uses for the existing drops, for which there are none:
 * `petz:bee_sting`
 * `petz:beaver_oil`
 * `petz:elephant_tusk`
 * `petz:pollen` (?!)
 * `petz:turtle_shell`
3. There's a number of uncraftable petz things, though I have no idea if there's secret recipes or something:
 * `petz:blue_stained_wood`
 * `petz:candy_cane`
 * `petz:gingerbread_cookie`
 * `petz:gray_paving_stone`
 * `petz:red_gables`
 * `petz:yellow_paving`

**Comment by KaylebJay** [comment]
Thanks! I will make a new issue with these problems because there are a lot more AFAIK.
