### ISSUE TITLE
xtraores ingots cannot be ground to dust

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#70]
I don't know whether this is intentional, acceptable, or worth fixing. It's not something that players would want to do very often.

**Comment by KaylebJay** [comment]
Why would players want to do it? :O

**Comment by fluxionary** [comment]
In my case, I wanted to test sticking stacks of dust from certain ores (rarium, adamantium, unobtanium) into the material reducer. But that didn't yield any results (with dust sourced from ore lumps), so I won't be needing it again for that purpose. I can't think of any other reasons except consistency. I thought I'd mention it, but I don't blame you if you decline this request.

**Comment by KaylebJay** [comment]
Yeah, I'll go with that. I'll put this into minetest-africa somewhere, when I get time

**Comment by KaylebJay** [comment]
Done
