### ISSUE TITLE
Nuclear bomb can't be placed anywhere

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#73]
:bug:z

**Comment by fluxionary** [comment]
This has to be recent, I placed and detonated one shortly after they first became a thing

**Comment by KaylebJay** [comment]
Yeah, it is.  I changed the API a bit because it was conflicting with something else...

**Comment by KaylebJay** [comment]
It seems this silly function not only conflicts with Hume2's underch but also my bee API. **weird**.

**Comment by KaylebJay** [comment]
Fixed
