### ISSUE TITLE
Some of abyssalart textures are whopping in size

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#74]
Currently some of the textures are almost a whole MB - something corrupted I guess.
The textures that are most badly affected are dyes and glass, opening them and exporting with GIMP takes all the bloat away somehow.
This should dramatically reduce client downloading (might go from 50MB to ... <5MB)

**Comment by KaylebJay** [comment]
Fixed, now abyssalart is only 1.8MB total.

**Comment by fluxionary** [comment]
For future reference, these tools are great:
* https://pmt.sourceforge.io/pngcrush/
* https://pngquant.org/

**Comment by KaylebJay** [comment]
Oh, awesome.
