### ISSUE TITLE
Limited time effects

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#75]
Potions that grant you effects for a limited time must come into existence.
Why? Because (1 flux (2 LadySparkles' head (3 Hume2 trying to tread lava in my volcano and eating a record 9000 golden apples (4 LadySparkles' glankles

The following limited time effects will happen when their happenings happen:
- [x] Speed Boost (increases speed by 2x)
- [x] Invisibility (makes you or an animal completely invisible including nametags)
- [x] Water Breathing (well, maybe this isn't the best name: grants you unlimited breath)
- [x] Lava Resistance (makes you immune to nodes in the igniter group)
- [x] Slow Falling (makes you fall much slower)
- [x] Jump Boost (makes you jump much higher)
- [x] Healing (recovers HP during the timespan, maybe 2 HP every second)
- [x] Harming (damages the player per second until dead, dunno why you would want to do this but it saves your fingers from typing /killme, I guess)

Coram suggested throwable potions, so I will add a few:
- [x] Exploding (throw - explodes on impact)
- [x] Damaging (throw - damages mobs in radius) (ONLY WORKS FOR DRACONIS right now, because of some problems in petz with the damaging system)
- [x] Teleporting (throw - teleports you to where the potion lands)

TO-DO:
- [x] Give potions time boosts with some rare material
- [x] Only one gravity related potion can be used at a time
- [x] Better player physics feel 
- [x] Recipes for all potions

and others which are :secret:z

The following items will be used for these potions:
`petz:spider_eye`
`petz:beaver_oil`
`petz:turtle_shell`
`africaplants:cortinarius_violaceus`
`africaplants:fire_essence`
`africaplants:fire_flower`
`africaplants:gerbera_oil`
`africaplants:lucky_club`
`africaplants:mint`
`africaplants:star_anise_plant`
`ethereal:fire_dust`
`ethereal:firethorn`
`ethereal:golden_apple`
`farming:carrot_gold`
Replaces https://github.com/KaylebJay/tunnelers-bugz/issues/21

**Comment by Hypernoot** [comment]
Let's hope that nobody gets the idea of mixing these potions IRL :D

**Comment by KaylebJay** [comment]
LOL :D

**Comment by KaylebJay** [comment]
An initial 'working' state has been committed. All that's left is textures and recipes for the potions!

**Comment by KaylebJay** [comment]
Done in minetest-africa, should be in server by tomorrow.
