### ISSUE TITLE
Request w.r.t. duration of night-vision goggles

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#76]
Really minor request, toss this one out the window w/out replying if you don't like it. 

The night vision goggles seem to last exactly 1 game day (20 minutes), which makes it so that if you activate the goggles at night, the next night there'll be a point where the goggles deactivate, plunging you suddenly into darkness. 

It'd feel much more natural if, instead, they lasted until the next morning (however long that is) instead of for a fixed period. That way, you still get to see evening and get a subtle cue that you need to use them again soon, but not immediately and unexpectedly.

**Comment by KaylebJay** [comment]
Sorry, I can't fix this. Its on globalstep, to make the night brighter by default so that newbies can see around without goggles ... which means that the override_day_or_night has to happen and thus overrides the goggles day_or_night_ratio.
