### ISSUE TITLE
Luacontrollers require manual intervention after server reboot

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#77]
After the server reboots, luacontrollers need to be reset before they will start working again.

**Comment by sivarajan931** [comment]
yeah that will be nice. but will that reset the code??

**Comment by fluxionary** [comment]
@SivarajanSam not sure what you mean. On other servers, where the admins haven't messed w/ mesecons to try to improve lag, the luacontrollers just work flawlessly between boots.

**Comment by KaylebJay** [comment]
Its a bug in the mesecons queues. Hume2 is investigating it.

**Comment by KaylebJay** [comment]
I believe this was fixed by the new updates to the queues. My controller is working fine now, Zeke too. @fluxionary Can you confirm - has your luacontroller gone between restarts, and continued working?

**Comment by KaylebJay** [comment]
Tested by flux and mesecons is now working properly again
