### ISSUE TITLE
Areas open

### ISSUE THREAD

**Issue by sivarajan931** [KaylebJay/tunnelers-bugz#78]
area_open for farming can be added for public farms for prevention of placement of other nodes other than farming seeds. this will prevent unnecessary digging of  the soil at farm.

**Comment by KaylebJay** [comment]
I don't understand what the goal is here. You should be able to just open the area that the seeds are in.
Does this have something to do with the technic planter/tractor?

**Comment by fluxionary** [comment]
Siva: There isn't an easy way to make an "open"-like area that only allows modifying crops, without some significant programming. The best option is to protect the whole farm, and create an open sub-area that's just at the level of the crops (1 layer right above the dirt usually, or for cactus & papyrus 4 or 5 nodes starting *above* the base of the plants). People can still grief the farm, but the damage can be minimized.

**Comment by KaylebJay** [comment]
This request doesn't really change anything unless the whole farm is used in the area_open command. Only the crops should be in the area_open command, then the only thing that can be taken is the crops. And if this was implemented it wouldn't prevent anyone from not replanting anyways.

**Comment by KaylebJay** [comment]
Oh, I see, people are placing dirt inside the area_open. Yeah, that'd be just way too hard to 'fix'. It seems like fixing the players would be easier :D
