### ISSUE TITLE
elements:light_* nodes can be obtained, somehow

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#82]
likely making them unpointable is the solution

**Comment by fluxionary** [comment]
Players say that they've gotten them after using a mining laser, are you sure you've correctly defined that they have no drop?

**Comment by KaylebJay** [comment]
That could very well be it, thanks for the report!

**Comment by fluxionary** [comment]
verified that i can get `elements:light_*` nodes by shooting the laser at another player's "feet", if they are holding a light source.

**Comment by KaylebJay** [comment]
Fixed in minetest-africa
