### ISSUE TITLE
Water extractor coverts wooden buckets to steel buckets

### ISSUE THREAD

**Issue by Desour** [KaylebJay/tunnelers-bugz#84]
Steps to reproduce:
- Place a water extractor.
- Put a wooden bucket with water into the lower slot.
- Put something to extract into the upper slot.
- Wait.
- Now there's an empty steel bucket in the lower slot.

**Comment by KaylebJay** [comment]
Wow, what a useful way to convert wood to iron! I'll look into it

**Comment by KaylebJay** [comment]
Should be fixed by this, once merged I will close.
https://gitlab.com/h2mm/technic/-/merge_requests/32
