### ISSUE TITLE
some/many kinds of wood don't work in the sawmill

### ISSUE THREAD

**Issue by AsumFace** [KaylebJay/tunnelers-bugz#88]

**Comment by KaylebJay** [comment]
I wonder how easy it would be to return all the 'trunk' and 'wood' finds. I guess you could do this with string.find and sending the result to singleplayer with minetest.chat_send_all?

**Comment by KaylebJay** [comment]
81 tree types, were, in fact, unsupported.
I have fixed this in minetest-africa.
