### ISSUE TITLE
Chainsaw should bring down lemons

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#90]
Possibly other fruit?

**Comment by KaylebJay** [comment]
Cherrytree leaves (green) aren't falling either. Also the moreton bay fig fruit.

**Comment by KaylebJay** [comment]
A lot of the cool_trees had fruits missing also. Merge request here - https://gitlab.com/h2mm/technic/-/merge_requests/34 - when merged I will close.
