### ISSUE TITLE
New torch behaviour

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#93]
Idea by @AsumFace
Two sticks in the crafting grid -> unlit torch
coal and stick in the crafting grid -> torch as usual. Hitting the torch once unlights it, hitting it again and you pick it up. (If this is too controversial then it could be right-click to unlight it, maybe). You can then light the unlit torch with flint & steel. (also could be done in crafting, maybe?)
Lit torches will never run out, still, just they can become unlit and relit.

**Comment by fluxionary** [comment]
I don't think this will be popular or successful. On all the servers I've seen where torches burn out (or damage the player if you stand on them), players just use a different kind of light source (typically `xdecor:candle`). This proposal isn't quite that "bad" but I expect it'll mostly just encourage players to not use torches. Then again most players already use super glow glass microblocks.

**Comment by KaylebJay** [comment]
The idea is not to make torches burn out, flux. This is specifically to let them be unlit or relit, for the purpose of building. Hence why I'll probably make the unlighting function on_rightclick instead.

**Comment by fluxionary** [comment]
Alright, sounds good.

**Comment by KaylebJay** [comment]
I believe the correct way to do this is override `default:flint_and_steel` so that on_punch, if pointed_thing is an unlit torch, it lights the torch (sets the node to a torch). However, this overrides paramtype, very sad. Is there a work around?
Similarly, on_rightclick for a torch to turn into an unlit torch overrides paramtype.

**Comment by KaylebJay** [comment]
Finished in minetest-africa.
Thanks to AsumFace for helping with the paramtype issue :)
