### ISSUE TITLE
the existential status of mobs:saddle

### ISSUE THREAD

**Issue by fluxionary** [KaylebJay/tunnelers-bugz#94]
`mobs:saddle` is a weird holdover. it's used to ride dragons, and that's it. it's craftable from mobs:leather, but there's no way to acquire that in TA. I feel like saddles need to be resolved; it may be that this has to wait on ElCeejo's next update. 

Possible resolutions, in order of my preference:
1. Alias one saddle to the other (i feel like this will fail to persist lots of behavior, that depends upon the ID of the item you are holding when you click/right click. 
2. Alter the code of `draconis` to use `petz:saddle`
3. Unify the leathers and create distinct recipes for the 2 kinds of saddle
4. Add `mobs:leather` as a drop from something, or otherwise obtainable somehow.

**Comment by KaylebJay** [comment]
3 is the one I've decided is going to be the best. 
Reasons: (1 paleotest also uses the mobs:saddle in the recent dev versions, (2 both leathers do not need to be there

**Comment by KaylebJay** [comment]
done in https://github.com/KaylebJay/petz/commit/d232a5c7e039f87950bebf6794b2f55949e349e5
