### ISSUE TITLE
Don't let tarantulas teleport in areas above -40

### ISSUE THREAD

**Issue by KaylebJay** [KaylebJay/tunnelers-bugz#95]
This is because, some people (`flux`, `LadySparkles25`, and others) get annoyed when they are teleported to in their home and I agree with them. Thanks to `kkp` and his son for screaming about it :)

**Comment by fluxionary** [comment]
Just noting that I'd prefer the logic to be "don't teleport into a protected area", but the proposed solution is acceptable. I've killed over 100 spiders already while building the underch museum...

**Comment by KaylebJay** [comment]
The problem with that (which I've weighed carefully) is that players could protect given mining regions to 'get away' from spiders, meaning an influx of (1 protected areas underground and (2 a bunch of useless protections for admins to deal with. So  keeping them *underground* seems to be the best way to handle this. 100 spiders, wow! I have only 141 spider eyes to my name at the moment, I need to get more. :)

**Comment by fluxionary** [comment]
i thought about that too, and decided it would be too much effort, but you're probably right that someone would, and i suppose it could become an annoying problem.

**Comment by KaylebJay** [comment]
Done in https://github.com/KaylebJay/petz/commit/8e929227ec31d25c3155a5e451fe75fea3006fa9
